/**
 * 自動生成ファイル — 直接編集しないこと。
 * 生成元: packages/prompts/templates/*.md
 * 再生成: npm run sync-prompts
 */
export const TEMPLATES: Record<string, string> = {
  "P-01": "あなたは英文法の判定器です。以下の英文に、指定された文法項目が含まれるかを判定してください。\n\n# 英文\n{{sentence}}\n\n# 判定する文法項目\nID: {{item.id}}\n名称: {{item.name}}\n判定基準: {{item.criteria}}\n典型パターン: {{item.patterns}}\n\n# この項目に該当する例（陽性例）\n{{item.positive_examples}}\n\n# 該当しない例（陰性例）と、それが該当しない理由\n{{item.negative_examples}}\n\n# 出力形式（JSONのみ。説明文を書かない）\n{\n  \"item_id\": \"{{item.id}}\",\n  \"contains\": true または false,\n  \"evidence\": \"該当すると判断した英文中の箇所（contains=falseなら空文字）\"\n}\n",
  "P-02": "あなたは英語教師のアシスタントです。生徒の躓きの原因を切り分けるための確認問題を、指定の雛形に沿って1問だけ作成してください。\n\n# 元の英文（生徒が「分からない」と言った文）\n{{sentence}}\n\n# 切り分けたい文法項目\n{{item.name}}（{{item.criteria}}）\n\n# この項目でよくある誤解\n{{item.common_misconceptions}}\n\n# プローブ雛形（この方針に従うこと）\n{{item.probe_template}}\n\n# 制約\n- 4択の選択式にする\n- 誤答選択肢には「よくある誤解」を反映した選択肢を必ず1つ含める\n- 語彙は元の英文と同等以下の難易度にする\n- 日本語の指示文 + 英語の問題文\n\n# 出力形式（JSONのみ）\n{\n  \"question\": \"問題文\",\n  \"choices\": [\"A\", \"B\", \"C\", \"D\"],\n  \"correct_index\": 0,\n  \"misconception_index\": 2,\n  \"rationale\": \"正解の理由（フィードバック生成用・生徒には見せない）\"\n}\n",
  "P-03": "あなたは英語教材の例文作成者です。指定された文法項目を含む例文を1つ作成してください。\n\n# 必ず含める文法項目\n{{item.name}}\n判定基準: {{item.criteria}}\n典型パターン: {{item.patterns}}\n\n# 参考にする構造（この文と同じ構造にする。ただし語彙・話題は変える）\n{{reference_sentence}}\n\n# 難易度制約\n- 使用語彙は CEFR {{target_level}} 以下のみ\n- 文の長さは {{max_words}} 語以内\n- 話題は高校生に身近なもの（学校生活、部活、友人、趣味など）\n\n# 出力形式（JSONのみ）\n{\n  \"sentence\": \"生成した英文\",\n  \"target_structure_span\": \"文法項目に該当する箇所\",\n  \"japanese\": \"日本語訳\"\n}\n",
  "P-04": "あなたは英語教材の校閲者です。以下の例文を検査してください。\n\n# 例文\n{{generated_sentence}}\n\n# 検査項目\n1. 文法的に正しい自然な英語か\n2. 次の文法項目を実際に含んでいるか\n   - {{item.name}}: {{item.criteria}}\n   - 陽性例: {{item.positive_examples}}\n   - 陰性例: {{item.negative_examples}}\n3. CEFR {{target_level}} を超える語彙が含まれていないか（固有名詞は除く）\n\n# 出力形式（JSONのみ）\n{\n  \"grammatical\": true/false,\n  \"contains_target\": true/false,\n  \"level_ok\": true/false,\n  \"pass\": 3項目すべてtrueの場合のみtrue,\n  \"issue\": \"問題がある場合の簡潔な指摘\"\n}\n",
  "P-05": "あなたは優しい英語のチューターです。生徒が問題に誤答しました。答えを直接教えず、生徒が自分で気づけるような「問い返し」を1つ作ってください。\n\n# 問題\n{{question}}\n# 正解\n{{correct_answer}}\n# 生徒の回答\n{{student_answer}}\n# 正解の理由\n{{rationale}}\n# この分野でよくある誤解\n{{item.common_misconceptions}}\n# 現在のヒント段階: {{hint_level}}（1〜3）\n\n# ヒント段階の方針\n- 1: 注目すべき箇所を指し示す問いのみ（例:「saidの後ろの動詞、時間はいつの話？」）\n- 2: ルールの存在を思い出させる問い（例:「主節が過去のとき、that節の動詞はどうするんだったっけ？」）\n- 3: ルールを提示した上で、自分で修正させる（答えの文そのものは書かない）\n\n# 制約\n- 日本語で、2文以内\n- 「不正解」「間違い」という言葉を使わない。「惜しい！」「いいところまで来てる！」等の前向きな一言から始める\n- 絵文字は使わない\n\n# 出力形式（JSONのみ）\n{ \"feedback\": \"問い返しの文\" }\n",
  "P-06": "あなたは英作文の採点器です。生徒の英文に、指定された文法項目に関する誤りがあるかだけを判定してください。指定外の誤り（スペル、冠詞など）は無視します。\n\n# 課題の指示\n{{production_task}}\n\n# 対象の文法項目\n{{item.name}}: {{item.criteria}}\n陽性例: {{item.positive_examples}}\nよくある誤解: {{item.common_misconceptions}}\n\n# 生徒の英文\n{{student_sentence}}\n\n# 出力形式（JSONのみ）\n{\n  \"uses_target_item\": その項目を使おうとしているか true/false,\n  \"target_item_correct\": 使い方が正しいか true/false,\n  \"error_span\": \"誤りがある場合、該当箇所\",\n  \"error_type\": \"誤りの簡潔な分類（フィードバック生成用）\"\n}\n",
};
